### ISSUE TITLE
Feature: Ignore urls option

### ISSUE THREAD

**Issue by HyperTHD** [Metropass/url_tester#12]
### If a user wants to ignore a url, the url_tester program should not make the request for that particular url. An example can be this:

* If a user has a ignore_case.txt and inside it includes ```www.google.ca```, then url_tester should not make a request to that url

I'd like to implement this feature for you as per lab 4 requirements.

Let me know if I get the ok!

**Comment by Metropass** [comment]
Noted! Assigned!

**Comment by HyperTHD** [comment]
efc4d3ef5178dae3cfaf3da374c19a77a1b23dea should hopefully fix this issue now. Thanks!
